
services:
  api:
    build: .
    container_name: api_main
    command: >
      sh -c "python -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - network_app_main

  nginx_main:
    image: nginx:1.29-alpine
    container_name: nginx_main
    ports:
      - "${NGINX_PORT}:80"  # Публикуем порт наружу
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Конфиг Nginx
    networks:
      - network_app_main


networks:
  network_app_main:
    driver: bridge
